web:
  restart: always
  build: ./web
  expose:
    - "5000"
  command: /usr/local/bin/gunicorn -w 2 -b :8000 run:server
  env_file: .env
  volumes:
    - ./web/data:/usr/src/app/web/data
    - /var/lib/postgresql/data:/var/lib/postgresql/data

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"

test:
  build: ./web
  expose:
    - "5000"
  env_file: .env
  environment:
    AUTHORIZATION_ENABLED: '0'
  command: bash test.sh
