web:
  restart: always
  build: ./web
  expose:
    - "5000"
  command: /usr/local/bin/gunicorn -w 2 -b :8000 api:server

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - web:web
