version: '2'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    expose:
      - "80"
    command: ./run-debug.sh
    env_file: .env
    volumes:
      - ./web:/usr/src/app/web
    links:
      - postgres:postgres
  postgres:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
